%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.17.11 on {{2015,4,25},{17,32,50}}

-ifndef(protocol).
-define(protocol, true).

-define(protocol_gpb_version, "3.17.11").

-record('Log',
        {id,                            % = 1, int32
         content,                       % = 2, string
         status,                        % = 3, int32
         times                          % = 4, int32
        }).

-record('Person',
        {id,                            % = 1, int32
         name,                          % = 2, string
         tags = [],                     % = 3, [int32]
         logs = []                      % = 4, [{msg,'Log'}]
        }).

-endif.
